GET http://localhost:3300/users/


###

GET http://localhost:3300/users/name

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "type",
  "password": "shit"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "name": "type",
  "password": "shit"
}

